// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookapi_minimal.AppContext;

#nullable disable

namespace BookStoreApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("bookapi_minimal.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("19a68475-0ada-44ea-b535-c1b6f66b6989"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("07a9024d-382c-4c02-9ba6-f811a142237b"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("7d3fc805-fa71-452e-ad4c-f57c607f510b"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("7d0e716a-3667-4c79-9f9f-0fdc2ebc3a74"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("16a01ace-afe7-4ed1-8a76-63e1d8473ff7"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        },
                        new
                        {
                            Id = new Guid("5400c880-af76-4f82-9a3c-57f2679c7063"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        },
                        new
                        {
                            Id = new Guid("faa408cb-4464-46f6-9e16-63e5c90ff912"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("f3160195-dba6-4274-9461-77c722e0e6b2"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("dec4ceee-fd8d-46bd-b31b-0a092439e430"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("1839bffc-4891-4b4d-9113-2876b0b11eea"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("3f0f09a6-3ab3-47ee-84fe-f4c58b24a98a"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        },
                        new
                        {
                            Id = new Guid("1332007d-7870-40ae-9cb3-d5ab9eafc39d"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
